AVR_TOOLS_DIR=/usr
BOARD_TAG = leonardo
ARDUINO_LIBS = Wire SPI Adafruit-GFX-Library-master Adafruit_SSD1306-master Encoder TimerOne-r11
AVRDUDE_CONF=/etc/avrdude/avrdude.conf
#ARDUINO_LIBS = Adafruit-GFX-Library-master
include /usr/share/arduino/Arduino.mk
